"""Captured Tuya OpenAPI fixtures for the real Steinbach WP Startis Inverto (modelId e1ktcz2k)."""

# Device descriptor as returned by /v1.0/iot-01/associated-users/devices, with
# the real device id, owner id, public IP and home coordinates replaced by dummy
# values. Only the fields the integration consumes are kept.
DEVICE = {
    'category': 'qn',
    'id': 'test_device_id',
    'model': '049310Z',
    'name': 'Wärmepumpe Startis Inverto',
    'online': True,
    'product_id': 'xiusqryqukyqkq3w',
    'product_name': 'Steinbach WP Startis Inverto/Silent Mini',
}

PROPERTIES = [   {   'code': 'switch',
        'custom_name': '',
        'dp_id': 1,
        'time': 1779999968162,
        'type': 'bool',
        'value': False},
    {   'code': 'temp_set',
        'custom_name': '',
        'dp_id': 2,
        'time': 1779999968166,
        'type': 'value',
        'value': 28},
    {   'code': 'temp_current',
        'custom_name': '',
        'dp_id': 3,
        'time': 1779999968407,
        'type': 'value',
        'value': 25},
    {   'code': 'mode',
        'custom_name': '',
        'dp_id': 4,
        'time': 1779999968612,
        'type': 'enum',
        'value': 'Heating'},
    {   'code': 'temp_unit_convert',
        'custom_name': '',
        'dp_id': 13,
        'time': 1779999969009,
        'type': 'enum',
        'value': 'c'},
    {   'code': 'fault',
        'custom_name': '',
        'dp_id': 21,
        'time': 1779999969211,
        'type': 'bitmap',
        'value': 0},
    {   'code': 'inwt_temp',
        'custom_name': '',
        'dp_id': 101,
        'time': 1779999969316,
        'type': 'value',
        'value': 25},
    {   'code': 'whj_temp',
        'custom_name': '',
        'dp_id': 102,
        'time': 1779999969612,
        'type': 'value',
        'value': 13},
    {   'code': 'cmp_temp',
        'custom_name': '',
        'dp_id': 103,
        'time': 1780001431716,
        'type': 'value',
        'value': 22},
    {   'code': 'p_temp',
        'custom_name': '',
        'dp_id': 104,
        'time': 1779999969917,
        'type': 'value',
        'value': 13},
    {   'code': 'outwt_temp',
        'custom_name': '',
        'dp_id': 105,
        'time': 1779999970210,
        'type': 'value',
        'value': 0},
    {   'code': 'return_temperature',
        'custom_name': '',
        'dp_id': 106,
        'time': 1780000341171,
        'type': 'value',
        'value': 20},
    {   'code': 'operating_frequency',
        'custom_name': '',
        'dp_id': 107,
        'time': 1779999970518,
        'type': 'value',
        'value': 0},
    {   'code': 'expansion_valve',
        'custom_name': '',
        'dp_id': 108,
        'time': 1779999970811,
        'type': 'value',
        'value': 350}]

MODEL = {   'modelId': 'e1ktcz2k',
    'services': [   {   'actions': [],
                        'code': '',
                        'description': '',
                        'events': [],
                        'name': '',
                        'properties': [   {   'abilityId': 1,
                                              'accessMode': 'rw',
                                              'code': 'switch',
                                              'description': '',
                                              'name': '开关',
                                              'typeSpec': {'type': 'bool'}},
                                          {   'abilityId': 2,
                                              'accessMode': 'rw',
                                              'code': 'temp_set',
                                              'description': '',
                                              'name': '目标温度',
                                              'typeSpec': {   'type': 'value',
                                                              'max': 45,
                                                              'min': 10,
                                                              'scale': 0,
                                                              'step': 1,
                                                              'unit': '℃'}},
                                          {   'abilityId': 3,
                                              'accessMode': 'ro',
                                              'code': 'temp_current',
                                              'description': '',
                                              'name': '当前温度',
                                              'typeSpec': {   'type': 'value',
                                                              'max': 99,
                                                              'min': -20,
                                                              'scale': 0,
                                                              'step': 1,
                                                              'unit': '℃'}},
                                          {   'abilityId': 4,
                                              'accessMode': 'rw',
                                              'code': 'mode',
                                              'description': '0制热，1制冷，',
                                              'name': '工作模式',
                                              'typeSpec': {   'type': 'enum',
                                                              'range': ['Heating', 'Cooling']}},
                                          {   'abilityId': 13,
                                              'accessMode': 'rw',
                                              'code': 'temp_unit_convert',
                                              'description': '',
                                              'name': '温标切换',
                                              'typeSpec': {'type': 'enum', 'range': ['c', 'f']}},
                                          {   'abilityId': 21,
                                              'accessMode': 'ro',
                                              'code': 'fault',
                                              'description': '标签：fault_b\n'
                                                             'it0,fault_bit\n'
                                                             '1,fault_bit2,\n'
                                                             'fault_bit3,fa\n'
                                                             'ult_bit4,faul\n'
                                                             't_bit5,fault_\n'
                                                             'bit6,fault_bi\n'
                                                             't7,fault_bit8\n'
                                                             ',fault_bit9,f\n'
                                                             'ault_bit10,fa\n'
                                                             'ult_bit11,fau\n'
                                                             'lt_bit12,faul\n'
                                                             't_bit13,fault\n'
                                                             '_bit14,fault_\n'
                                                             'bit15,fault_b\n'
                                                             'it16,fault_bi\n'
                                                             't17,fault_bit\n'
                                                             '18,fault_bit1\n'
                                                             '9,fault_bit20\n'
                                                             ',fault_bit21,\n'
                                                             'fault_bit22,f\n'
                                                             'ault_bit23,fa\n'
                                                             'ult_bit24,fau\n'
                                                             'lt_bit25,faul\n'
                                                             't_bit26,fault\n'
                                                             '_bit27,fault_\n'
                                                             'bit28,fault_b\n'
                                                             'it29',
                                              'extensions': {'scope': 'fault'},
                                              'name': '故障告警',
                                              'typeSpec': {   'type': 'bitmap',
                                                              'label': [   'fault_bit0',
                                                                           'fault_bit1',
                                                                           'fault_bit2',
                                                                           'fault_bit3',
                                                                           'fault_bit4',
                                                                           'fault_bit5',
                                                                           'fault_bit6',
                                                                           'fault_bit7',
                                                                           'fault_bit8',
                                                                           'fault_bit9',
                                                                           'fault_bit10',
                                                                           'fault_bit11',
                                                                           'fault_bit12',
                                                                           'fault_bit13',
                                                                           'fault_bit14',
                                                                           'fault_bit15',
                                                                           'fault_bit16',
                                                                           'fault_bit17',
                                                                           'fault_bit18',
                                                                           'fault_bit19',
                                                                           'fault_bit20',
                                                                           'fault_bit21',
                                                                           'fault_bit22',
                                                                           'fault_bit23',
                                                                           'fault_bit24',
                                                                           'fault_bit25',
                                                                           'fault_bit26',
                                                                           'fault_bit27',
                                                                           'fault_bit28',
                                                                           'fault_bit29'],
                                                              'maxlen': 30}},
                                          {   'abilityId': 101,
                                              'accessMode': 'ro',
                                              'code': 'inwt_temp',
                                              'description': '进水温度',
                                              'name': '进水温度',
                                              'typeSpec': {   'type': 'value',
                                                              'max': 99,
                                                              'min': -30,
                                                              'scale': 0,
                                                              'step': 1,
                                                              'unit': '℃'}},
                                          {   'abilityId': 102,
                                              'accessMode': 'ro',
                                              'code': 'whj_temp',
                                              'description': '环境温度',
                                              'name': '环境温度',
                                              'typeSpec': {   'type': 'value',
                                                              'max': 99,
                                                              'min': -30,
                                                              'scale': 0,
                                                              'step': 1,
                                                              'unit': '℃'}},
                                          {   'abilityId': 103,
                                              'accessMode': 'ro',
                                              'code': 'cmp_temp',
                                              'description': '排气温度',
                                              'name': '排气温度',
                                              'typeSpec': {   'type': 'value',
                                                              'max': 99,
                                                              'min': -30,
                                                              'scale': 0,
                                                              'step': 1,
                                                              'unit': '℃'}},
                                          {   'abilityId': 104,
                                              'accessMode': 'ro',
                                              'code': 'p_temp',
                                              'description': '盘管温度',
                                              'name': '盘管温度',
                                              'typeSpec': {   'type': 'value',
                                                              'max': 99,
                                                              'min': -30,
                                                              'scale': 0,
                                                              'step': 1,
                                                              'unit': '℃'}},
                                          {   'abilityId': 105,
                                              'accessMode': 'ro',
                                              'code': 'outwt_temp',
                                              'description': '出水温度',
                                              'name': '出水温度',
                                              'typeSpec': {   'type': 'value',
                                                              'max': 99,
                                                              'min': -30,
                                                              'scale': 0,
                                                              'step': 1,
                                                              'unit': '℃'}},
                                          {   'abilityId': 106,
                                              'accessMode': 'ro',
                                              'code': 'return_temperature',
                                              'description': '回气温度',
                                              'name': '回气温度',
                                              'typeSpec': {   'type': 'value',
                                                              'max': 99,
                                                              'min': -30,
                                                              'scale': 0,
                                                              'step': 1,
                                                              'unit': '℃'}},
                                          {   'abilityId': 107,
                                              'accessMode': 'ro',
                                              'code': 'operating_frequency',
                                              'description': '',
                                              'name': '压机频率',
                                              'typeSpec': {   'type': 'value',
                                                              'max': 100,
                                                              'min': 0,
                                                              'scale': 0,
                                                              'step': 1,
                                                              'unit': 'HZ'}},
                                          {   'abilityId': 108,
                                              'accessMode': 'ro',
                                              'code': 'expansion_valve',
                                              'description': '',
                                              'name': '电子膨胀阀开度',
                                              'typeSpec': {   'type': 'value',
                                                              'max': 500,
                                                              'min': 0,
                                                              'scale': 0,
                                                              'step': 1,
                                                              'unit': 'P'}}]}]}

DEVICE_ID = DEVICE["id"]
